---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs_on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: python manage.py test
      - name: Lint
        run: flake8