---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: pip install flake8
      - run: pip install -r requirements.txt

      - name: Test
        run: python manage.py test
      - name: Lint
        run: cd flixapp/
        run: flake8